config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :images, only: [:create, :destroy] do
    post :remove, :unremove, :share, :effect, on: :member
    get :versions, on: :member
    get :removed, on: :collection
  end
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :user
  has_many :share_images, dependent: :destroy
  validates_presence_of :user_id, :version, :avatar
  validates_uniqueness_of :version, scope: :origin_image_id
  validates_numericality_of :version, greater_than_or_equal_to: 1, allow_nil: true

  default_scope { where(removed: false).order("origin_image_id") }

  mount_uploader :avatar, AvatarUploader

  def shareable_users
    User.where.not(id: self.user_id)
  end

  def shared?(user_id)
    self.share_images.where(shared_user_id: user_id).present?
  end

  def remove
    self.where_same_origin.each do |image|
      image.update!(removed: true)
    end
  end

  def unremove
    self.where_same_origin.each do |image|
      image.update!(removed: false)
    end
  end

  def full_destroy
    self.where_same_origin.each do |image|
      image.destroy
    end
  end

  def where_same_origin
    Image.unscoped.where(origin_image_id: self.origin_image_id)
  end

  def create_version(filter)
    Image.create!(version: last_version + 1,
                  user_id: user_id,
                  origin_image_id: origin_image_id,
                  avatar: File.open(avatar.public_send(filter).split(" ").first)
                 )
  end

  def last_version
    Image.where(origin_image_id: self.origin_image_id).map(&:version).max
  end

  def self.last_version
    self.select{|image| image.version == image.last_version}
  end
end

app/models/share_image.rb
class ShareImage < ActiveRecord::Base
  belongs_to :shared_user, class_name: :User
  belongs_to :image

  validates_presence_of :image_id, :shared_user_id
  validates_uniqueness_of :image_id, scope: :shared_user_id

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  has_many :share_images

  validates_presence_of :email, :name

  def was_shared_images
    Image.joins(:share_images).where(share_images: { shared_user_id: self.id })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_user
    redirect_to root_path unless current_user
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :require_user
  before_action :set_image, only: [:remove, :unremove, :destroy, :share, :effect, :versions]

  def create
    @image = Image.new image_params.merge(version: 1)
    @image.save!
    @image.update!(origin_image_id: @image.id)

    redirect_to root_path
  end

  def remove
    @image.remove
    redirect_to root_path
  end

  def unremove
    @image.unremove
    redirect_to root_path
  end

  def removed
    @images = Image.unscoped.where(user_id: current_user.id, removed: true).last_version
  end

  def versions
    @images = Image.unscoped.where(origin_image_id: @image.origin_image_id)
  end

  def share
    user_id = params[:shared_user_id].to_i
    if @image.shared? user_id
      @image.share_images.find_by_shared_user_id(user_id).destroy!
    else
      @image.share_images.create!(shared_user_id: user_id)
    end
    redirect_to root_path
  end

  def effect
    @image.create_version(params[:filter])
    redirect_to root_path
  end

  def destroy
    @image.full_destroy
    redirect_to removed_images_path
  end

  private

  def set_image
    @image = Image.unscoped.where(user_id: current_user.id).find(params[:id])
  end

  def image_params
    params.require(:image).permit(:avatar, :avatar_cache).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    if current_user
      @image = Image.new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/removed.html.erb
<h3>Deleted Images:</h3>
<% @images.each do |image| %>
  <div class="pull-left">
    <%= image_tag image.avatar.url, style: 'height: 200px; margin-left: 15px' %>
    <br>
    <%= link_to "Versions", versions_image_path(image), style: "margin-left: 50px" %>
    <%= link_to "Restore", unremove_image_path(image), method: :post, style: "margin-left: 50px" %>
    <%= link_to "Fully delete", image, method: :delete, style: "margin-left: 50px" %>
  </div>
<% end %>

app/views/images/versions.html.erb
<h3>All Versions:</h3>
<% @images.each do |image| %>
  <div class="pull-left">
    <%= image_tag image.avatar.url, style: 'height: 200px; margin-left: 15px; margin-top: 30px' %>
    <br>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Share Your Images!" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>
  Welcome!
  <% if current_user %>
    <%= current_user.name %>
  <% end %>
</h3>

<% if current_user %>
  <div class="pull-left">
    <%= form_for @image, :html => { :multipart => true } do |f| %>
      <%= f.label :avatar, 'Upload image:'%>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %>
      <br />
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="pull-right">
    <%= link_to removed_images_path do %>
      <i class="glyphicon glyphicon-trash" style="font-size: 30px; margin-left: 30px"></i>
      <br>
      Deleted images
    <% end %>
  </div>

  <br style="clear: both">
  <h3>Uploaded Files:</h3>
  <% current_user.images.last_version.each do |image| %>
    <div class="pull-left">
      <%= image_tag image.avatar.url, style: 'height: 200px; margin-left: 15px; margin-top: 30px' %>
      <br>

      <!-- Share -->
      <div class="dropdown pull-left", style="margin-left: 18px">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
          Share To:
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <% image.shareable_users.each do |user|%>
            <li>
              <%= link_to user.name + (image.shared?(user.id) ? " √" : ""), share_image_path(image, shared_user_id: user.id), method: :post %>
            </li>
          <% end %>
        </ul>
      </div>

      <!-- Filters -->
      <div class="dropdown pull-left", style="margin-left: 18px">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
          Filters
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <% AvatarUploader::Filters.each do |filter|%>
            <li>
              <%= link_to filter.titleize, effect_image_path(image, filter: filter), method: :post %>
            </li>
          <% end %>
        </ul>
      </div>

      <%= link_to "Versions", versions_image_path(image), style: "margin-left: 35px" %>
      <%= link_to "Delete", remove_image_path(image), method: :post, style: "margin-left: 35px" %>
    </div>
  <% end %>

  <!-- Shared images by other users -->
  <br style="clear: both">
  <br>
  <h3>Shared images by other users:</h3>
  <% current_user.was_shared_images.last_version.each do |image| %>
    <div class="pull-left">
      <%= image_tag image.avatar.url, style: 'height: 200px; margin-left: 15px; margin-top: 30px' %>
      <br>
    </div>
  <% end %>
<% end %>